s = open('C:/Users/Administrator/.openclaw/workspace/rubii-self/server.js','r',encoding='utf-8').read()
s = s.replace('ensureDir(CHARS_DIR);\nensureDir(CHATS_DIR);\n', '')
s = s.replace('ensureDir(CHARS_DIR);', '')
s = s.replace('ensureDir(CHATS_DIR);', '')
s = s.replace('ensureDir(UPLOADS_DIR);', '')
s = s.replace("path.join(CHATS_DIR, charId + '.json')", "path.join(userChatsDir(username), charId + '.json')")
lines = s.split('\n')
filtered = [l for l in lines if 'const UPLOADS_DIR' not in l]
s = '\n'.join(filtered)
open('C:/Users/Administrator/.openclaw/workspace/rubii-self/server.js','w',encoding='utf-8').write(s)
print('Fixed')
